// Code generated by generate_datasets.go; DO NOT EDIT.
package stats_test

import "github.com/montanaflynn/stats"


// Anscombe1 generates Anscombe1 dataset
func Anscombe1() []stats.Coordinate {
	return []stats.Coordinate{
		{ 10.00, 8.04},{ 8.00, 6.95},{ 13.00, 7.58},{ 9.00, 8.81},{ 11.00, 8.33},{ 14.00, 9.96},{ 6.00, 7.24},{ 4.00, 4.26},{ 12.00, 10.84},{ 7.00, 4.82},{ 5.00, 5.68},
	}
}

// Anscombe2 generates Anscombe2 dataset
func Anscombe2() []stats.Coordinate {
	return []stats.Coordinate{
		{ 10.00, 9.14},{ 8.00, 8.14},{ 13.00, 8.74},{ 9.00, 8.77},{ 11.00, 9.26},{ 14.00, 8.10},{ 6.00, 6.13},{ 4.00, 3.10},{ 12.00, 9.13},{ 7.00, 7.26},{ 5.00, 4.74},
	}
}

// Anscombe3 generates Anscombe3 dataset
func Anscombe3() []stats.Coordinate {
	return []stats.Coordinate{
		{ 10.00, 7.46},{ 8.00, 6.77},{ 13.00, 12.74},{ 9.00, 7.11},{ 11.00, 7.81},{ 14.00, 8.84},{ 6.00, 6.08},{ 4.00, 5.39},{ 12.00, 8.15},{ 7.00, 6.42},{ 5.00, 5.73},
	}
}

// Anscombe4 generates Anscombe4 dataset
func Anscombe4() []stats.Coordinate {
	return []stats.Coordinate{
		{ 8.00, 6.58},{ 8.00, 5.76},{ 8.00, 7.71},{ 8.00, 8.84},{ 8.00, 8.47},{ 8.00, 7.04},{ 8.00, 5.25},{ 19.00, 12.50},{ 8.00, 5.56},{ 8.00, 7.91},{ 8.00, 6.89},
	}
}

